### ISSUE TITLE
setup fails: No such file or directory: 'HISTORY.rst'

### ISSUE THREAD

**Issue by jayvdb** [ar4s/flake8_tuple#1]
```
Collecting flake8-tuple
  Downloading flake8_tuple-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-xoicxx/flake8-tuple/setup.py", line 14, in <module>
        with open('HISTORY.rst') as history_file:
    IOError: [Errno 2] No such file or directory: 'HISTORY.rst'
```

**Comment by ar4s** [comment]
Thanks for issue!

**Comment by ar4s** [comment]
Fixed
