### ISSUE TITLE
Support for older flake8 versions broken

### ISSUE THREAD

**Issue by jayvdb** [ar4s/flake8_tuple#11]
#9 forces the use of `pycodestyle`, instead of `pep8`, but older versions of flake8 do not include pycodestyle, so on flake8 241 for example, the following occurs:

```
470 flakes-v241 runtests: commands[0] | flake8 --version
471 Traceback (most recent call last):
472   File ".tox/flakes-v241/bin/flake8", line 11, in <module>
473     sys.exit(main())
474   File "/home/magnum/flake8-putty/.tox/flakes-v241/local/lib/python2.7/site-packages/flake8/main.py", line 25, in main
475     flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
476   File "/home/magnum/flake8-putty/.tox/flakes-v241/local/lib/python2.7/site-packages/flake8/engine.py", line 111, in get_style_guide
477     kwargs['parser'], options_hooks = get_parser()
478   File "/home/magnum/flake8-putty/.tox/flakes-v241/local/lib/python2.7/site-packages/flake8/engine.py", line 49, in get_parser
479     (extensions, parser_hooks, options_hooks, ignored) = _register_extensions()
480   File "/home/magnum/flake8-putty/.tox/flakes-v241/local/lib/python2.7/site-packages/flake8/engine.py", line 33, in _register_extensions
481     checker = entry.load(require=False)
482   File "/home/magnum/flake8-putty/.tox/flakes-v241/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
483     return self.resolve()
484   File "/home/magnum/flake8-putty/.tox/flakes-v241/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
485     module = __import__(self.module_name, fromlist=['__name__'], level=0)
486   File "/home/magnum/flake8-putty/.tox/flakes-v241/local/lib/python2.7/site-packages/flake8_tuple.py", line 4, in <module>
487     import pycodestyle
488 ImportError: No module named pycodestyle
```

The way I have worked around this is to use `flake8.engine.pep8` , which is consistently the right thing for all flake8 versions up to (but not including) v3

https://github.com/jayvdb/flake8-putty/commit/4d2e1530f7b8814fcbec641f50b6e94a9952622a

**Comment by ar4s** [comment]
@jayvdb thanks for the report! Try new version (0.2.11) from pypi.
