### ISSUE TITLE
Compatibility with flake8 3.0

### ISSUE THREAD

**Issue by The-Compiler** [ar4s/flake8_tuple#12]
Seems like 745051ee3e239d62210e52668105e30214dd7fb7 broke again with the final flake8 3.0 release :worried: 

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 159, in load_plugin
    self._load(verify_requirements)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8/plugins/manager.py", line 137, in _load
    self._plugin = resolve()
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/florian/proj/qutebrowser/git/.tox/flake8/lib/python3.5/site-packages/flake8_tuple.py", line 8, in <module>
    from flake8.engine import pep8
ImportError: No module named 'flake8.engine'
```

It looks like you should probably use something like:

```
try:
    import pycodestyle as pep8
except ImportError:
    import pep8
```

as well as using `flake8-polyfill` (according to the [flake8 docs](http://flake8.pycqa.org/en/latest/plugin-development/cross-compatibility.html#standard-in-handling-on-flake8-2-5-2-6-and-3)) to get correct behaviour with all versions...

**Comment by ar4s** [comment]
Thanks! Please upgrade to 0.2.12

**Comment by The-Compiler** [comment]
Thanks again for the quick update! I'll give it a try soon, but currently I'm staying on flake8 2 as I'm waiting for the `hacking` plugin to be updated too :wink:
