### ISSUE TITLE
TokenError: EOF in multi-line string

### ISSUE THREAD

**Issue by jayvdb** [ar4s/flake8_tuple#6]
A TokenError occurs whenever a docstring has three lines.

```bash
$ cat test.py
"""
foo

"""
bah = 1
$ flake8 test.py
Traceback (most recent call last):
  File "/usr/bin/flake8", line 9, in <module>
    load_entry_point('flake8==2.5.4', 'console_scripts', 'flake8')()
  File "/usr/lib/python2.7/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pep8.py", line 1842, in check_files
    runner(path)
  File "/usr/lib/python2.7/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/usr/lib/python2.7/site-packages/pep8.py", line 1574, in check_all
    self.check_ast()
  File "/usr/lib/python2.7/site-packages/pep8.py", line 1521, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/usr/lib/python2.7/site-packages/flake8_tuple-0.2.7-py2.7.egg/flake8_tuple.py", line 37, in run
    noqa = get_noqa_lines(lines)
  File "/usr/lib/python2.7/site-packages/flake8_tuple-0.2.7-py2.7.egg/flake8_tuple.py", line 52, in get_noqa_lines
    for x in tokens
  File "/usr/lib64/python2.7/tokenize.py", line 302, in generate_tokens
    raise TokenError, ("EOF in multi-line string", strstart)
tokenize.TokenError: ('EOF in multi-line string', (1, 0))
```

**Comment by jayvdb** [comment]
fwiw, this was found when using this extension against the codebase at https://github.com/wikimedia/pywikibot-core
Here is my changeset to enable this extension
https://gerrit.wikimedia.org/r/#/c/274075/

**Comment by ar4s** [comment]
@jayvdb try upgrade to 0.2.8

**Comment by jayvdb** [comment]
bingo!  this plugin now passes the pywikibot code. much appreciated!
